// Todo-ReactJS/todo-app/src/todo-input/todo-input.js
import React from 'react'
import './todo-input.css'

const todoInput = (props) => {

    return (
        <div className="container">
            <input
                type="text"
                placeholder="Enter Todo"
                className="todo--input"
                value={props.value}
                onChange={props.changed} />

            <button
                type="button"
                className="btn save"
                onClick={props.clicked}
                disabled={props.disabled}>
                Save Todo!</button>
        </div>
    )

}



export default todoInput;

// Todo-Angular/todo-app/src/app/todo-input/todo-input.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'app-todo-input',
    templateUrl: './todo-input.component.html',
    styleUrls: ['./todo-input.component.css']
})
export class TodoInputComponent {

    // tslint:disable-next-line:no-output-on-prefix
    @Output() onTodoAdd: EventEmitter<any> = new EventEmitter<any>();
    todo: String = '' ;

    onSaveTodo() {
        this
        .onTodoAdd
        .emit(this.todo);
    }
}

<div class="container">

    <input  
    [(ngModel)]="todo" 
    type="text" 
    placeholder="Enter Todo" 
    class="todo--input"/>

    <button 
    [disabled]="todo == ''" 
    type="button" 
    class="btn save" 
    (click)="onSaveTodo()">Save Todo!</button>

</div>
