// Todo-ReactJS/todo-app/src/todo-list/todo-list.js
import React from 'react'
import './todo-list.css'

const todoList = (props) => {
    return (
        <div className="container">
            <input
                type="text"
                className="todo--input"
                value={props.value}
                disabled={true} />

            <button
                type="button"
                className="btn delete"
                onClick={props.deleteTodo}
            >Delete
            </button>

        </div>
    )
}
export default todoList;

// Todo-Angular/todo-app/src/app/todo-list/todo-list.component.ts
import { Component, Input } from '@angular/core';
import { TodoService } from '../shared/todo-storage.service';

@Component({
    selector: 'app-todo-list',
    templateUrl: './todo-list.component.html',
    styleUrls: ['./todo-list.component.css']
})

export class TodoListComponent  {

    @Input() todo: string;
    @Input() index: number;

    constructor(private todoService: TodoService) { }

    onDeleteTodo() {
        this
        .todoService
        .changeTodo(this.index);
    }
}

<div class="container">

    <input  
    [disabled]="true" 
    type="text" 
    placeholder="Enter Todo" 
    class="todo--input" 
    [(ngModel)]="todo"/>
    
    <button 
    type="button" 
    class="btn delete" 
    (click)="onDeleteTodo()">Delete</button>

</div>
