// Todo-VueJS/todo-app/src/App.vue
<template>
  <div id="app">
    <div class="container--todo-header">
      <h1>Todo App VueJS</h1>
    </div>
    <todoInput @onTodoAdd = "handleTodoAdd"></todoInput>
    <hr/>
    <div v-for="(todo,index) in todos" 
    :key="index" 
    class="margin-top-50">
      <todoList
      @onDeleteTodo = "handleDeleteTodo"
      :todoEl="todo"
      :todoInd="index"></todoList>
    </div>
  </div>
</template>

<script>
import todoInput from './components/todo-input/todo-input'
import todoList from './components/todo-list/todo-list.vue'
export default {
  name: 'App',
  data() {
    return {
      todos: []
    }
  },
  methods: {
    handleTodoAdd(todo) {
      this.todos.push(todo)
    },
    handleDeleteTodo(ind) {
      this
      .todos
      .splice(ind,1)
    }
  },
  components: {
    todoInput,
    todoList
  }
}
</script>

<style>
.container--todo-header {
  display: flex;
  justify-content: center;
}
.margin-top-50 {
  margin-top: 50px;
}
</style>

// Todo-Angular/todo-app/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from './shared/todo-storage.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  todos: any = [];
  constructor(private todoService: TodoService) {}

  ngOnInit() {
    this.todoService.
    todoObserverIndex.
    subscribe(todo_index => {
    this.todos.splice(todo_index, 1);
    });
  }
  handleTodoAdd(todo: String): void {
    this.todos.push(todo);
  }

}

<div class="container--todo-header">
  <h1>Todo App Angular</h1>
</div>
<app-todo-input (onTodoAdd)="handleTodoAdd($event)"></app-todo-input>
<hr>
<div class="margin-top-50">
  <app-todo-list 
    [todo]="todoEl" 
    [index]="i" 
    *ngFor="let todoEl of todos;let i = index">
  </app-todo-list>
</div>
